### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [wotakuro/ScreenshotToUnityProfiler#2]
Hi @wotakuro,

Thanks for making this awesome UPM package. I'm the creator of [OpenUPM](https://openupm.com) platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 200+ open-source UPM packages at the time of writing.

To make it happen, I would suggest you make GitHub releases (which create Git tags) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

Then you can submit your package here: https://openupm.com/packages/add/

**Comment by wotakuro** [comment]
Hi thank you for your information.
(maybe) I did it.
I made release tag!

**Comment by favoyang** [comment]
It works! https://openupm.com/packages/com.utj.screenshot2profiler/
